// import "../styles/reset.css";
import "../styles/globals.css";
import type { AppProps } from "next/app";
import type { Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { Toaster, ToasterProps } from "react-hot-toast";
import Head from "next/head";

interface AuthProp {
    session: Session;
}

type MyAppProps = AppProps<AuthProp>;

function MyApp({
    Component,
    pageProps: { session, ...pageProps },
}: MyAppProps) {
    const toastConfig: ToasterProps = {
        position: "top-center",
        gutter: 2,
    };
    return (
        <>
            <SessionProvider session={session}>
                <Head>
                    <title>Shortly</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    {/* <link rel="icon" href="/favicon.ico" /> */}
                </Head>
                <Toaster {...toastConfig} />
                <Component {...pageProps} />
            </SessionProvider>
        </>
    );
}

export default MyApp;
