import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

interface ILink {
    title: string;
    link: string;
}

interface HomeProps {
    data: {
        links: ILink[];
    };
}

const Home: NextPage<HomeProps> = ({ data }) => {
    const links = data.links;

    const [input, setInput] = useState("");
    console.log(input);

    console.log(links);
    return (
        <div className="flex justify-center">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1 className="font-bold underline ">Teste</h1>
                {links.map((item) => (
                    <p key={item.title} className="text-center">
                        {item.title} - {item.link}
                    </p>
                ))}
                <Link href="/about">
                    <p className="text-center underline text-blue-500 cursor-pointer">
                        teste
                    </p>
                </Link>
                <input
                    type="text"
                    className="bg-green-100"
                    value={input}
                    onChange={(event) => {
                        setInput(event.target.value);
                    }}
                />
                <Link
                    href={`/profile/${input}`}
                    className="bg-gray-300 hover:bg-white"
                >
                    Ir para profile
                </Link>
            </main>
        </div>
    );
};

export const getStaticProps = () => {
    return {
        props: {
            data: {
                links: [
                    { title: "whatever", link: "youtube.com" },
                    { title: "cute bunny", link: "youtube.com" },
                ],
            },
        },
    };
};

export default Home;
